version: 0.4.0.{build}

environment:
    global:
        SDL_AUDIODRIVER: "disk"


    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python27-x64"

install:
    # Fetch submodules
    - git submodule update --init --recursive

    # get windows deps
    - curl -fsSL -o xxx.zip http://fofix.net/downloads/fofix-win32-deppack-20130304-updated.zip
    - 7z x xxx.zip
    - dir
    - dir fofix-win32-deppack-20130304-updated
    - dir fofix-win32-deppack-20130304-updated\deps
    - move fofix-win32-deppack-20130304-updated\deps fretwork\win32\
    - dir fretwork\win32\
    - xcopy build.cmd fretwork\
    

    # We need wheel installed to build wheels
    - "%PYTHON%\\python.exe -m pip install wheel"

    # Install python deps
    - "%PYTHON%\\python.exe -m pip install cython"

build: off

build_script:
    - cd fretwork
    - "build.cmd %PYTHON%\\python.exe -m setup.py build_ext --inplace --force"
    - "build.cmd %PYTHON%\\python.exe -m setup.py sdist"
    - "build.cmd %PYTHON%\\python.exe -m setup.py bdist_wheel"


artifacts:
    - path: fretwork\dist\*
