version: 0.4.2.{build}

environment:
    global:
        SDL_AUDIODRIVER: "disk"


    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python27-x64"

install:
    # Fetch submodules
    - git submodule update --init --recursive

    # get windows deps
    #- curl -fsSL -o xxx.zip http://fofix.net/downloads/fofix-win32-deppack-20130304-updated.zip
    #- 7z x xxx.zip
    # https://superuser.com/a/546694/562968
    #- curl -fsSL -o xxx.tar.gz https://github.com/Linkid/win-dependencies/releases/download/0.1/fretwork-win32-deppack-20190425.tar.gz
    - curl -fsSL -o xxx.tar.gz https://github.com/Linkid/win-dependencies/releases/download/0.2/fretwork-win32-deppack-20190531.tar.gz
    - 7z x xxx.tar.gz -so | 7z x -aoa -si -ttar -o"fofix-win32-deppack-20130304-updated"
    - dir
    - dir fofix-win32-deppack-20130304-updated
    - dir fofix-win32-deppack-20130304-updated\deps
    - mkdir fretwork\win32
    - move fofix-win32-deppack-20130304-updated\deps fretwork\win32\
    - dir fretwork\win32\
    - xcopy build.cmd fretwork\
    - cmd: @echo %PKG_CONFIG_LIBDIR%
    - cmd: echo %PKG_CONFIG_LIBDIR%
    - cmd: echo %PKG_CONFIG_PATH%
    - cmd: deps\bin\pkg-config.exe --list-all

    # We need wheel installed to build wheels
    - "%PYTHON%\\python.exe -m pip install wheel"

    # Install python deps
    - "%PYTHON%\\python.exe -m pip install cython"

build: off

build_script:
    - cd fretwork
    - "build.cmd %PYTHON%\\python.exe setup.py build_ext --inplace --force"
    - "build.cmd %PYTHON%\\python.exe setup.py sdist"
    - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"


artifacts:
    - path: fretwork\dist\*
