language: python
python:
    - 2.7
    - 3.6

install:
    - pip install fretwork

script:
    - python -c "from fretwork.mixstream import VorbisFileMixStream"
    - python -c "from fretwork.mixstream import *"
