language: python
python:
    - 2.7
    - 3.6

install:
    - LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH
    - sudo apt-add-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install gcc-4.9 g++-4.9
    - pip install fretwork

script:
    - python -c "from fretwork.mixstream import VorbisFileMixStream"
    - python -c "from fretwork.mixstream import *"
