env:
    global:
        - REPO_DIR=fretwork
        - BUILD_COMMIT=0.3.0
        # pip dependencies
        - BUILD_DEPENDS="Cython numpy Pillow PyOpenGL Pygame"
        # pip dependencies for tests
        - TEST_DEPENDS="pytest"
        - PLAT=x86_64
        - UNICODE_WIDTH=32
        #- WHEELHOUSE_UPLOADER_USERNAME=travis-worker

language: python
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  exclude:
    # Exclude the default Python 3.5 build
    - python: 3.5
  include:
    - os: linux
      env: MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

#after_success:
#    # Upload wheels to PyPI
#    - pip install wheelhouse-uploader
#    - python -m wheelhouse_uploader upload --local-folder
#        ${TRAVIS_BUILD_DIR}/wheelhouse/
#        --no-update-index
#        wheels
