language: python
python:
    - 2.7
    - 3.6

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            #- gcc-4.9
            - g++-4.9

install:
    - LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH
    - pip install fretwork

script:
    - python -c "from fretwork.mixstream import VorbisFileMixStream"
    - python -c "from fretwork.mixstream import *"
